### ISSUE TITLE
SQL error at activation

### ISSUE THREAD

**Issue by Guibock** [SecSign/SecSign-ID-Nextcloud-Plugin#1] opened 2019-03-05 20:25 UTC
On Nextcloud 15.0.5. 
Tried to download and activate this plugin from the Apps admin page. 
An error has shown up : `An exception occurred while executing 'ALTER TABLE oc_secsignid ADD id INT AUTO_INCREMENT DEFAULT 1 NOT NULL': SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'id'`

**Comment by secsignid** [comment] 2019-03-08 10:46
Hi,

can you give us some more information about the database you will use?

Greetings
The SecSign Team

**Comment by Guibock** [comment] 2019-03-08 11:46
Hello,

Here are the information about my server and the database:

 

Database server

    Server: Localhost via UNIX socket
    Server type: MariaDB
    Server connection: SSL is not being used Documentation
    Server version: 10.1.38-MariaDB - MariaDB Server
    Protocol version: 10
    User: me@localhost
    Server charset: UTF-8 Unicode (utf8)

 

Web server

    cpsrvd 11.78.0.16
    Database client version: libmysql - 5.1.73
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.2.7

 

Server Information
    Apache Version     2.4.38
    PHP Version     7.0.33
    MySQL Version     10.1.38-MariaDB
    Architecture     x86_64
    Operating System     linux
    Path to Sendmail     /usr/sbin/sendmail
    Path to Perl     /usr/bin/perl
    Perl Version     5.10.1
    Kernel Version     2.6.32-042stab123.2

 

 

When I try to install from the Nextcloud App admin panel, here is what I see :

 



 

Thanks,

Guillaume.


 

 


Envoyé: vendredi 8 mars 2019 à 11:46
De: "SecSign Technologies Inc." <notifications@github.com>
À: SecSign/SecSign-ID-Nextcloud-Plugin <SecSign-ID-Nextcloud-Plugin@noreply.github.com>
Cc: Guibock <gverdun@gmx.fr>, Author <author@noreply.github.com>
Objet: Re: [SecSign/SecSign-ID-Nextcloud-Plugin] SQL error at activation (#1)


Hi,

can you give us some more information about the database you will use?

Greetings
The SecSign Team

**Comment by deafgaminghd** [comment] 2019-03-09 09:53
i having same error that you recviced....

**Comment by secsignid** [comment] 2019-03-11 12:51
Hi,

this issue was caused by a slight difference in the strictness of MySQL/MariaDB and SQLite. It has been resolved in update 0.1.2 via commit [be9495d](https://github.com/SecSign/SecSign-ID-Nextcloud-Plugin/commit/be9495d09f28413260706a145aac402998dd1542).

Thank you for reporting this issue .

Greetings,
The SecSign Team

**Closed as completed by secsignid** 2019-03-11 12:51 UTC

**Comment by deafgaminghd** [comment] 2019-03-11 17:26
Issues new-

"There is no column with name 'id' on table 'oc_secsignid'
